<SpinnerOption>:



<Informe>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.name
        ScrollView:
            id: scroll_view
            BoxLayout:
                id: main_container
                orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: 'Volver a generador'
                on_press: root.btn_volver()
